#!/bin/bash

echo "Enter the table number:"
read n

echo "Enter the range:"
read range

echo "Multiplication table for $n up to range $range"

for ((i=1; i<=range; i++))
do
    res=$((n*i))
    echo "$n * $i = $res"
done
